const $=id=>document.getElementById(id), LABELS={behavior_bar:'行为窗口柱状图',line:'折线图',scatter:'散点图',box:'箱线图',bar:'计数柱状图',hist:'直方图',heatmap:'相关性热图'}, CLASSES=['stationary','bathing','flight_take_off','flight_cruising','foraging_dive','body_shaking','surface_seizing','preening','dipping'], NAMES=['Stationary','Bathing','Take-off','Cruising flight','Foraging dive','Body shaking','Surface seizing','Preening','Dipping'];let filesData=[],combined=[],columns=[],rec=null,lastRows=[];
function csvParse(text){text=text.replace(/^\uFEFF/,'');let rows=[],row=[],cell='',q=false;for(let i=0;i<text.length;i++){let ch=text[i];if(q){if(ch==='"'&&text[i+1]==='"'){cell+='"';i++}else if(ch==='"')q=false;else cell+=ch}else if(ch==='"')q=true;else if(ch===','){row.push(cell);cell=''}else if(ch==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=ch}if(cell||row.length){row.push(cell);rows.push(row)}let head=rows.shift()?.map(x=>x.trim())||[];return rows.filter(r=>r.some(x=>x.trim())).map(r=>Object.fromEntries(head.map((h,i)=>[h,(r[i]??'').trim()]))) }
function isNum(v){return v!==''&&v!=null&&Number.isFinite(Number(v))}function readText(file){return new Promise((resolve,reject)=>{let fr=new FileReader;fr.onerror=reject;fr.onload=()=>{let a=new Uint8Array(fr.result),txt;try{txt=new TextDecoder('utf-8',{fatal:true}).decode(a)}catch{txt=new TextDecoder('gbk').decode(a)}resolve(txt)};fr.readAsArrayBuffer(file)})}
async function load(list){try{$('error').hidden=true;filesData=[];for(const f of list){const rows=csvParse(await readText(f));if(!rows.length)throw Error(`${f.name} 没有可读取的数据行。`);filesData.push({name:f.name,rows})}combined=filesData.flatMap(f=>f.rows.map(r=>({...r,_source_file:f.name})));columns=[...new Set(combined.flatMap(Object.keys))].filter(x=>x!=='_source_file');showOverview();setup()}catch(e){$('error').textContent=e.message||'读取失败，请检查 CSV 格式。';$('error').hidden=false}}
const input=$('files'),drop=$('drop');input.onchange=()=>load(input.files);drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag')};drop.ondragleave=()=>drop.classList.remove('drag');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('drag');load(e.dataTransfer.files)};
function showOverview(){$('fileList').innerHTML=filesData.map(f=>`<span class="file-chip">${esc(f.name)} · ${f.rows.length.toLocaleString()} 行</span>`).join('');$('mFiles').textContent=filesData.length;$('mRows').textContent=combined.length.toLocaleString();$('mCols').textContent=columns.length;$('mMissing').textContent=combined.reduce((n,r)=>n+columns.filter(c=>!r[c]).length,0).toLocaleString();renderTable('preview',combined.slice(0,100),columns);$('overview').hidden=false;$('settings').hidden=false}
function profile(){let nums=columns.filter(c=>combined.filter(r=>r[c]!=='').slice(0,500).every(r=>isNum(r[c]))),times=columns.filter(c=>/time|date|日期|时间/i.test(c)&&combined.filter(r=>r[c]).slice(0,50).filter(r=>!isNaN(Date.parse(r[c]))).length>=Math.max(1,combined.filter(r=>r[c]).slice(0,50).length*.7)),cats=columns.filter(c=>!nums.includes(c)&&!times.includes(c));return{nums,times,cats}}
function recommend(){let p=profile();if(columns.includes('label'))return{type:'behavior_bar',x:'label',y:'',title:'海鸟行为分布',text:'识别到项目标准的 label 列，使用纯标签滑动窗口算法生成行为计数柱状图。'};if(p.times.length&&p.nums.length)return{type:'line',x:p.times[0],y:p.nums[0],title:`${p.nums[0]} 随时间变化`,text:'识别到时间变量和连续变量，推荐使用折线图观察变化趋势。'};if(p.nums.length>=3)return{type:'heatmap',x:'',y:'',title:'连续变量相关性热图',text:'识别到多个连续变量，推荐使用相关性热图观察变量间关系。'};if(p.nums.length>=2)return{type:'scatter',x:p.nums[0],y:p.nums[1],title:`${p.nums[0]} 与 ${p.nums[1]}`,text:'识别到两个连续变量，推荐使用散点图观察它们的关系。'};if(p.cats.length&&p.nums.length)return{type:'box',x:p.cats[0],y:p.nums[0],title:`不同 ${p.cats[0]} 的 ${p.nums[0]} 分布`,text:'识别到分类变量和连续变量，推荐使用箱线图比较各组分布。'};if(p.cats.length)return{type:'bar',x:p.cats[0],y:'',title:`${p.cats[0]} 计数`,text:'识别到分类变量，推荐使用柱状图展示各类别计数。'};return{type:'hist',x:p.nums[0]||columns[0],y:'',title:`${p.nums[0]||columns[0]} 分布`,text:'推荐使用直方图展示数值分布。'}}
function setup(){rec=recommend();$('recTitle').textContent=LABELS[rec.type];$('recText').textContent=rec.text;$('chartType').innerHTML=Object.entries(LABELS).filter(([k])=>k!=='behavior_bar'||columns.includes('label')).map(([k,v])=>`<option value="${k}">${v}</option>`).join('');let opts='<option value="">不使用</option>'+columns.map(c=>`<option>${esc(c)}</option>`).join('');['xVar','yVar','groupVar'].forEach(id=>$(id).innerHTML=opts);$('chartType').value=rec.type;$('xVar').value=rec.x||'';$('yVar').value=rec.y||'';$('title').value=rec.title;toggleWindows()}
$('chartType').onchange=toggleWindows;function toggleWindows(){let on=$('chartType').value==='behavior_bar';$('windowLabel').hidden=!on;$('strideLabel').hidden=!on}
$('generate').onclick=()=>{try{generate()}catch(e){$('error').textContent=e.message;$('error').hidden=false;$('error').scrollIntoView({behavior:'smooth'})}};
function norm(v){return String(v??'').trim().toLowerCase().replaceAll(' ','_').replace('take-off','flight_take_off').replace('takeoff','flight_take_off').replace('cruising_flight','flight_cruising')}
function behavior(){let size=+$('windowSize').value,stride=+$('stride').value,counts=Object.fromEntries(CLASSES.map(x=>[x,0]));for(const f of filesData){for(let i=0;i+size<=f.rows.length;i+=stride){let w=f.rows.slice(i,i+size).map(r=>norm(r.label));if(w.every(x=>x===w[0])&&CLASSES.includes(w[0]))counts[w[0]]++}}return CLASSES.map((c,i)=>({behavior:NAMES[i],count:counts[c]}))}
function generate(){let type=$('chartType').value,x=$('xVar').value,y=$('yVar').value,title=$('title').value||LABELS[type],rows;if(type==='behavior_bar')rows=behavior();else if(type==='bar'){let m={};combined.forEach(r=>m[r[x]||'Missing']=(m[r[x]||'Missing']||0)+1);rows=Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,30).map(([category,count])=>({category,count}))}else rows=combined;lastRows=draw(type,rows,x,y,title);$('summary').textContent=type==='behavior_bar'?`按窗口大小 ${$('windowSize').value}、步长 ${$('stride').value} 统计，共识别到 ${rows.reduce((n,r)=>n+r.count,0)} 个标签完全一致的有效行为窗口。`:`系统使用 ${LABELS[type]} 展示所选数据，共使用 ${combined.length.toLocaleString()} 行记录。`;$('usedFiles').textContent=filesData.map(f=>f.name).join('、');$('usedChart').textContent=LABELS[type];renderTable('resultTable',lastRows.slice(0,1000),Object.keys(lastRows[0]||{}));$('result').hidden=false;$('result').scrollIntoView({behavior:'smooth'})}
function canvas(){let el=$('chart'),d=devicePixelRatio||1,w=el.clientWidth,h=el.clientHeight;el.width=w*d;el.height=h*d;let c=el.getContext('2d');c.scale(d,d);c.clearRect(0,0,w,h);c.fillStyle='#fff';c.fillRect(0,0,w,h);return{c,w,h,p:55}}
function axes(c,w,h,p,title,x='',y=''){c.strokeStyle='#9fb5b8';c.beginPath();c.moveTo(p,p);c.lineTo(p,h-p);c.lineTo(w-p,h-p);c.stroke();c.fillStyle='#18343b';c.font='bold 18px system-ui';c.textAlign='center';c.fillText(title,w/2,28);c.font='12px system-ui';c.fillText(x,w/2,h-10);c.save();c.translate(15,h/2);c.rotate(-Math.PI/2);c.fillText(y,0,0);c.restore()}
function draw(type,rows,x,y,title){let {c,w,h,p}=canvas(),out=[];axes(c,w,h,p,title,x,y);if(['behavior_bar','bar'].includes(type)){let lab=type==='behavior_bar'?'behavior':'category',vals=rows.map(r=>+r.count),max=Math.max(...vals,1),bw=(w-p*2)/rows.length*.7;rows.forEach((r,i)=>{let xx=p+(i+.15)*(w-p*2)/rows.length,hh=(h-p*2)*r.count/max;c.fillStyle='#167d8d';c.fillRect(xx,h-p-hh,bw,hh);c.save();c.translate(xx+bw/2,h-p+8);c.rotate(-.55);c.fillStyle='#405f65';c.textAlign='right';c.font='11px system-ui';c.fillText(r[lab],0,0);c.restore();c.textAlign='center';c.fillStyle='#18343b';c.fillText(r.count,xx+bw/2,h-p-hh-5)});out=rows}
else if(type==='line'){let pts=rows.map(r=>({x:Date.parse(r[x]),y:+r[y]})).filter(q=>isFinite(q.x)&&isFinite(q.y)).sort((a,b)=>a.x-b.x);plotPoints(c,w,h,p,pts,true);out=pts}
else if(type==='scatter'){let pts=rows.map(r=>({x:+r[x],y:+r[y],group:$('groupVar').value?r[$('groupVar').value]:''})).filter(q=>isFinite(q.x)&&isFinite(q.y));plotPoints(c,w,h,p,pts,false);out=pts}
else if(type==='hist'){let vals=rows.map(r=>+r[x]).filter(Number.isFinite),bins=Math.min(30,Math.max(5,Math.floor(Math.sqrt(vals.length)))),mn=Math.min(...vals),mx=Math.max(...vals),step=(mx-mn||1)/bins,arr=Array.from({length:bins},(_,i)=>({range:`${(mn+i*step).toFixed(2)}–${(mn+(i+1)*step).toFixed(2)}`,count:0}));vals.forEach(v=>arr[Math.min(bins-1,Math.floor((v-mn)/step))].count++);out=draw('bar',arr.map(r=>({category:r.range,count:r.count})),'','','')}
else if(type==='box'){let groups={};rows.forEach(r=>{let v=+r[y];if(Number.isFinite(v))(groups[r[x]||'Missing']??=[]).push(v)});out=Object.entries(groups).slice(0,20).map(([group,v])=>{v.sort((a,b)=>a-b);let q=t=>v[Math.floor((v.length-1)*t)];return{group,min:v[0],q1:q(.25),median:q(.5),q3:q(.75),max:v.at(-1)}});drawBoxes(c,w,h,p,out)}
else if(type==='heatmap'){let nums=profile().nums.slice(0,12);out=nums.map(a=>Object.fromEntries(['variable',...nums].map(b=>b==='variable'?[b,a]:[b,corr(rows,a,b)])));drawHeat(c,w,h,p,out,nums)}return out}
function plotPoints(c,w,h,p,pts,line){if(!pts.length)throw Error('所选变量没有可绘制的有效数值。');let xs=pts.map(q=>q.x),ys=pts.map(q=>q.y),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),sx=v=>p+(v-xmin)/(xmax-xmin||1)*(w-2*p),sy=v=>h-p-(v-ymin)/(ymax-ymin||1)*(h-2*p);c.strokeStyle='#167d8d';c.fillStyle='#167d8d';c.beginPath();pts.slice(0,10000).forEach((q,i)=>{let xx=sx(q.x),yy=sy(q.y);if(line){i?c.lineTo(xx,yy):c.moveTo(xx,yy)}else{c.moveTo(xx+3,yy);c.arc(xx,yy,3,0,Math.PI*2)}});line?c.stroke():c.fill()}
function drawBoxes(c,w,h,p,a){let all=a.flatMap(r=>[r.min,r.max]),mn=Math.min(...all),mx=Math.max(...all),sy=v=>h-p-(v-mn)/(mx-mn||1)*(h-2*p),slot=(w-2*p)/a.length;a.forEach((r,i)=>{let x=p+(i+.5)*slot;c.strokeStyle='#167d8d';c.strokeRect(x-slot*.25,sy(r.q3),slot*.5,sy(r.q1)-sy(r.q3));c.beginPath();c.moveTo(x-slot*.25,sy(r.median));c.lineTo(x+slot*.25,sy(r.median));c.moveTo(x,sy(r.min));c.lineTo(x,sy(r.q1));c.moveTo(x,sy(r.q3));c.lineTo(x,sy(r.max));c.stroke();c.save();c.translate(x,h-p+8);c.rotate(-.5);c.fillStyle='#405f65';c.textAlign='right';c.fillText(r.group,0,0);c.restore()})}
function corr(rows,a,b){let p=rows.map(r=>[+r[a],+r[b]]).filter(v=>v.every(Number.isFinite)),n=p.length;if(!n)return 0;let ax=p.reduce((s,v)=>s+v[0],0)/n,bx=p.reduce((s,v)=>s+v[1],0)/n,num=0,da=0,db=0;p.forEach(v=>{let x=v[0]-ax,y=v[1]-bx;num+=x*y;da+=x*x;db+=y*y});return +(num/Math.sqrt(da*db)||0).toFixed(3)}
function drawHeat(c,w,h,p,rows,names){let sz=Math.min((w-2*p)/names.length,(h-2*p)/names.length);rows.forEach((r,i)=>names.forEach((n,j)=>{let v=r[n],a=Math.abs(v),rgb=v>=0?`22,125,141`:`190,70,65`;c.fillStyle=`rgba(${rgb},${.1+.9*a})`;c.fillRect(p+j*sz,p+i*sz,sz,sz);c.fillStyle=a>.55?'white':'#18343b';c.textAlign='center';c.fillText(v.toFixed(2),p+(j+.5)*sz,p+(i+.58)*sz)}))}
function renderTable(id,rows,cols){$(id).innerHTML='<thead><tr>'+cols.map(c=>`<th>${esc(c)}</th>`).join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+cols.map(c=>`<td>${esc(r[c]??'')}</td>`).join('')+'</tr>').join('')+'</tbody>'}function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('downloadPng').onclick=()=>{let a=document.createElement('a');a.download='seabird_visualization.png';a.href=$('chart').toDataURL('image/png');a.click()};$('printPdf').onclick=()=>window.print();window.onresize=()=>{if(!$('result').hidden)$('generate').click()};
